export const TRIP_STATUS = {
    REQUESTED: "REQUESTED",
    ACCEPTED: "ACCEPTED",
    DRIVER_ARRIVING: "DRIVER_ARRIVING",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
    REJECTED: "REJECTED",
};